name: mne-march2
channels:
  - conda-forge
dependencies:
  - python=3.8.6
  # - c-ares=1.17.1
  # - glib=2.66.3
  # - imageio-ffmpeg=0.4.2
  - jupyter=1.0.0
  - matplotlib=3.3.3
  # - jupyter_nbextensions_configurator=0.4.1
  # - libllvm10=10.0.1
  # - libpq=12.3
  # - libvorbis=1.3.7
  # - mffpy=0.5.8
  - mne=0.21.2
  # - mysql-libs=8.0.21
  # - pexpect=4.8.0
  - pip=20.2
  # - pyvistaqt=0.2.0
  - seaborn=0.11.1
  # - spyder-kernels=1.10.0
  - zarr=2.7.0
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - autoreject==0.2.2
    - cachetools==4.1.1
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.3
    - mne-features==0.2
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    # This seems like it simply doesn't exist at all...
    # - scikit-rvm==0.1.0a1
    - sklearn-rvm==0.1.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.4.1
    - tensorflow-addons==0.11.2
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.5.0.dev2020123101
    - typeguard==2.10.0
    - typing-extensions==3.7.4.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
